### ISSUE TITLE
Rod lengths!

### ISSUE THREAD

**Issue by zorgrian** [dherrendoerfer/uCNC_controller#1]
## Size matters

I would like to know the lengths of the rods used in this CNC machine. I have looked hard at contents of this repository. I have also watched the great videos by Dirk on youtube.
I want to make one of these things or something like it. I should like to know the lengths of the 5mm rod used in the current designs as a starting place.

**Comment by dherrendoerfer** [comment]
The rod lengths are basically up to the person building it.
For a 160x100mm work area I'd use 220mm rod for the X, and 180mm for the Y Axis.
