### ISSUE TITLE
STL files for Plotter_v4

### ISSUE THREAD

**Issue by pevire** [dherrendoerfer/uCNC_controller#2]
Hello, could you upload .stl files for every part of Plotter_v4?

I'd like to print every part separately and I really don't know how to split parts in the file wich contents all the parts together.

Thanks in advance.

**Comment by dherrendoerfer** [comment]
Uploaded. 
Cheers !

**Comment by pevire** [comment]
Thanks a lot.

2018-01-10 20:55 GMT+01:00 dherrendoerfer <notifications@github.com>:

**Comment by laziiii** [comment]
hello this is the part of cnc plotter I lived in the city could send me these costly parts
