### ISSUE TITLE
Rod-Robin cad files?

### ISSUE THREAD

**Issue by Aianir** [dherrendoerfer/uCNC_controller#7]
Would you be able to share the cad files for the Rod-Robin? I'd like to adapt them to using the 8mm rods, threaded rods and bearings that I already have.

**Comment by dherrendoerfer** [comment]
I can't share them publicly on github , because the of the license agreement with SketchUp, but I can share them privately.

**Comment by Aianir** [comment]
That will work! I added you to a private repository here on github, if you can share them there that would be great!
